# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuLung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='seo',
            name='img',
            field=models.ImageField(null=True, upload_to=b'seo_image'),
        ),
        migrations.AddField(
            model_name='seo',
            name='title',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='seo',
            name='type',
            field=models.CharField(default=b'website', max_length=1024),
        ),
        migrations.AddField(
            model_name='seo',
            name='url_address',
            field=models.URLField(null=True),
        ),
    ]
