# Generated by Django 2.1.4 on 2018-12-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuLung', '0002_auto_20180131_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(upload_to='banners_image'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='img',
            field=models.ImageField(null=True, upload_to='seo_image'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='type',
            field=models.CharField(default='website', max_length=1024),
        ),
    ]
