# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuLung', '0002_auto_20171222_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seo',
            name='tag',
        ),
        migrations.AddField(
            model_name='ticket',
            name='reminder',
            field=models.TextField(max_length=2048, null=True),
        ),
    ]
