# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuLung', '0003_auto_20180125_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='reminder',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
