# Generated by Django 2.1.4 on 2018-12-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuLung', '0003_auto_20181230_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='seo',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='seo_image'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reminder',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
