# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 02:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuLung', '0004_auto_20180126_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reported_customer_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
