# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='validation_key',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
