# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_orders_validation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerstype',
            name='available_service',
            field=models.ManyToManyField(to='reservation.ServicesType'),
        ),
    ]
