# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 18:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_customerstype_available_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerstype',
            name='session_time_lenth',
        ),
        migrations.AddField(
            model_name='servicestype',
            name='for_family',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicestype',
            name='service_fee',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
