# Generated by Django 2.1.4 on 2018-12-29 19:14

import django.core.validators
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_customerdetails_phone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='license_plate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerstype',
            name='customers_type_image',
            field=sorl.thumbnail.fields.ImageField(upload_to='customers_type_image'),
        ),
        migrations.AlterField(
            model_name='servicestype',
            name='service_type_image',
            field=sorl.thumbnail.fields.ImageField(upload_to='services_type_image'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='available_manpower',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='capacity',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
