# Generated by Django 2.1.4 on 2018-12-31 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20181230_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='transportation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='code',
            field=models.CharField(blank=True, default='', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='license_plate',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='number_of_customer',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='validation_key',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='servicestype',
            name='service_note',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
